### ISSUE TITLE
Not working. Localization problem?

### ISSUE THREAD

**Issue by damocles-stonith** [MathijsNL/WhatsappTime#2]
Hello:

I installed the extension in Firefox, but it does not work.

I read the code and the regular expression does not seem to match the text.

Code:
const re = /^(\d\d?):(\d\d) ([aApP])[mM]$/

Text from my browser: 
4:17 p. m.

Dots and spaces will break the regular expression. Is it a localization problem?

**Comment by MathijsNL** [comment]
Yes it is.
![image](https://user-images.githubusercontent.com/1612886/164276423-929870be-6ea0-4c74-8af8-e09eb28124b7.png)

A guy from Israel messaged me because for him it was capital A/P M. And now you have dots and spaces.

I will update the plugin soon to match the text from your browser, thanks for sharing this.

**Comment by MathijsNL** [comment]
@damocles-stonith I just updated the code in the repository, I need to do some final testing before pushing to Firefox addons / Chrome webstore.

If you would like to test this make sure to change manifest version to 2 in manifest.json because Firefox doesn't like manifest version 3.

Edit:
New version is available in the Firefox addon store, you can just install it now. Let me know if it got fixed for you.

**Comment by damocles-stonith** [comment]
Hi @MathijsNL 

Thanks for your time. The problem persists. I tried to debug (it is the first time i do it) but I do not see any code loaded. I do not know if I am debugging correctly

![imagen](https://user-images.githubusercontent.com/104084752/164316491-91376246-c4e3-4008-89ad-2fc550c2eac6.png)

**Comment by MathijsNL** [comment]
It seems to be working for a. m. time. Will look into it.

Edit:
Small oversight in the regex. I am going to push a fix for it.

Edit2:
I just pushed the extension to Firefox addon store. Can you check again please?

**Comment by MathijsNL** [comment]
I think this got fixed, if not let me know!
